// <auto-generated />
using System;
using Destiny_back.Modules;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Destiny_back.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Destiny_back.Modules.EntityTypes.Activity", b =>
                {
                    b.Property<long>("ActivityHash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("MilestoneHash")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityHash");

                    b.HasIndex("MilestoneHash");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("Destiny_back.Modules.EntityTypes.Milestone", b =>
                {
                    b.Property<long>("Hash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("QuestItemHash")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("VendorHash")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Hash");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Destiny_back.Modules.EntityTypes.Modifier", b =>
                {
                    b.Property<long>("ModifierHash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ActivityHash")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModifierHash");

                    b.HasIndex("ActivityHash");

                    b.ToTable("Modifiers");
                });

            modelBuilder.Entity("Destiny_back.Modules.EntityTypes.Activity", b =>
                {
                    b.HasOne("Destiny_back.Modules.EntityTypes.Milestone", "Milestone")
                        .WithMany("Activities")
                        .HasForeignKey("MilestoneHash");
                });

            modelBuilder.Entity("Destiny_back.Modules.EntityTypes.Modifier", b =>
                {
                    b.HasOne("Destiny_back.Modules.EntityTypes.Activity", "Activity")
                        .WithMany("Modifiers")
                        .HasForeignKey("ActivityHash");
                });
#pragma warning restore 612, 618
        }
    }
}
