version: '3.4'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: destiny-back-sql
    environment:
        SA_PASSWORD: "MyPassword001"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  destiny-back:
    image: ${DOCKER_REGISTRY-}destinyback
    build:
      context: .
      dockerfile: Destiny-back/Dockerfile
    depends_on:
     - mssql
    ports:
      - "778:1444"